### ISSUE TITLE
XLSX Date Format

### ISSUE THREAD

**Issue by mkolodner** [ArdenKolodner/CCI-SQL-XLSX-Importer-Exporter#2]
Not a new or unknown issue, but filing it here for documentation. When the dataset is converted to Excel, any date fields should have their columns set to be strings. 
(Otherwise Excel converts a date the user might enter into a useless format.)

**Comment by ArdenKolodner** [comment]
Dates are now converted to strings in the latest version, using the YYYY-MM-DD format that seems to be CCI's format. If it turns out that CCI uses other date/datetime formats as well, we can reopen this.
